# Generated by Django 3.2 on 2022-09-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_courseteachers_day_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseteachers',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('course', 'num')},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='courseteachers',
            name='day_birth',
            field=models.DateField(verbose_name='Birth date'),
        ),
    ]
